import Image from "next/image";
import Link from "next/link";

export const metadata = {
    title: "Next",
    description: "Generated by create next app",
};


export default function Test() {
    return (
        <main className="flex flex-col justify-center items-center pb-20">
            <div className="z-10 max-w-5xl w-full items-center justify-between font-mono text-sm lg:flex mt-20">
                <div className="bg-yellow-300 w-full h-10 flex">
                    <Link className=" h-full flex items-center justify-center" href={"/"}>
                        <div className="bg-red-500 items-center flex px-5">
                            <span className="">LOGO</span>
                        </div>
                    </Link>
                    <div className="flex items-center justify-end bg-green-300 w-full gap-5 px-3">
                        <span>Nav 1</span>
                        <span>Nav 2</span>
                        <span>Nav 3</span>
                    </div>
                </div>
            </div>
            <div className="content bg-white w-full max-w-5xl mt-10 p-5 ">

                <h1 className="text-2xl">Bagian utama: Lorem Ipsum</h1>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt bibendum finibus. Curabitur sed libero ac ex dapibus rhoncus non sed massa. Duis sed imperdiet erat, vitae mattis mi. Pellentesque viverra interdum mi. Cras a volutpat odio, vel molestie tortor. Ut ut ornare orci. Aenean feugiat arcu vel ullamcorper mollis. Donec consectetur risus dapibus urna finibus, id venenatis nibh sodales. Sed non metus non enim laoreet elementum eu finibus risus. Morbi eget mattis diam. Donec efficitur egestas urna eu volutpat. Suspendisse finibus mattis arcu. Praesent sit amet nunc eleifend, vulputate felis ut, vehicula quam.

                    Mauris commodo urna nec libero porta suscipit. Quisque eu eleifend nibh. Curabitur congue ac leo ac pretium. Proin nibh lectus, gravida vel turpis eget, vulputate molestie orci. Nam neque libero, tempus sed bibendum eu, interdum elementum diam. Pellentesque varius tincidunt commodo. Proin id justo scelerisque risus porttitor consequat eget mollis leo. Maecenas quis lacus sem. Suspendisse tincidunt urna posuere ante dictum bibendum. Proin ac condimentum elit, mollis dignissi
                    m lorem.</p>
                <br />
            </div>
            <div className="flex w-full max-w-5xl">
                <div className="h-10 w-1 bg-gray-600 ml-10"></div>
            </div>
            <div className="content bg-white w-full max-w-5xl p-5">
                <h1 className="text-2xl">Metode Penelitian</h1>
                <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt bibendum finibus. Curabitur sed libero ac ex dapibus rhoncus non sed massa. Duis sed imperdiet erat, vitae mattis mi. Pellentesque viverra interdum mi. Cras a volutpat odio, vel molestie tortor. Ut ut ornare orci. Aenean feugiat arcu vel ullamcorper mollis. Donec consectetur risus dapibus urna finibus, id venenatis nibh sodales. Sed non metus non enim laoreet elementum eu finibus risus. Morbi eget mattis diam. Donec efficitur egestas urna eu volutpat. Suspendisse finibus mattis arcu. Praesent sit amet nunc eleifend, vulputate felis ut, vehicula quam.

                    Mauris commodo urna nec libero porta suscipit. Quisque eu eleifend nibh. Curabitur congue ac leo ac pretium. Proin nibh lectus, gravida vel turpis eget, vulputate molestie orci. Nam neque libero, tempus sed bibendum eu, interdum elementum diam. Pellentesque varius tincidunt commodo. Proin id justo scelerisque risus porttitor consequat eget mollis leo. Maecenas quis lacus sem. Suspendisse tincidunt urna posuere ante dictum bibendum. Proin ac condimentum elit, mollis dignissim lorem.</span>
            </div>
            <div className="flex w-full max-w-5xl">
                <div className="h-10 w-1 bg-gray-600 ml-10"></div>
            </div>
            <div className="content bg-white w-full max-w-5xl p-5">
                <h1 className="text-2xl">Latar belakang</h1>
                <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt bibendum finibus. Curabitur sed libero ac ex dapibus rhoncus non sed massa. Duis sed imperdiet erat, vitae mattis mi. Pellentesque viverra interdum mi. Cras a volutpat odio, vel molestie tortor. Ut ut ornare orci. Aenean feugiat arcu vel ullamcorper mollis. Donec consectetur risus dapibus urna finibus, id venenatis nibh sodales. Sed non metus non enim laoreet elementum eu finibus risus. Morbi eget mattis diam. Donec efficitur egestas urna eu volutpat. Suspendisse finibus mattis arcu. Praesent sit amet nunc eleifend, vulputate felis ut, vehicula quam.

                    Mauris commodo urna nec libero porta suscipit. Quisque eu eleifend nibh. Curabitur congue ac leo ac pretium. Proin nibh lectus, gravida vel turpis eget, vulputate molestie orci. Nam neque libero, tempus sed bibendum eu, interdum elementum diam. Pellentesque varius tincidunt commodo. Proin id justo scelerisque risus porttitor consequat eget mollis leo. Maecenas quis lacus sem. Suspendisse tincidunt urna posuere ante dictum bibendum. Proin ac condimentum elit, mollis dignissim lorem.</span>
            </div>
            <div className="flex w-full max-w-5xl">
                <div className="h-10 w-1 bg-gray-600 ml-10"></div>
            </div>
            <div className="content bg-white w-full max-w-5xl p-5">
                <h1 className="text-2xl">Dokumentasi</h1>
                <span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut tincidunt bibendum finibus. Curabitur sed libero ac ex dapibus rhoncus non sed massa. Duis sed imperdiet erat, vitae mattis mi. Pellentesque viverra interdum mi. Cras a volutpat odio, vel molestie tortor. Ut ut ornare orci. Aenean feugiat arcu vel ullamcorper mollis. Donec consectetur risus dapibus urna finibus, id venenatis nibh sodales. Sed non metus non enim laoreet elementum eu finibus risus. Morbi eget mattis diam. Donec efficitur egestas urna eu volutpat. Suspendisse finibus mattis arcu. Praesent sit amet nunc eleifend, vulputate felis ut, vehicula quam.

                    Mauris commodo urna nec libero porta suscipit. Quisque eu eleifend nibh. Curabitur congue ac leo ac pretium. Proin nibh lectus, gravida vel turpis eget, vulputate molestie orci. Nam neque libero, tempus sed bibendum eu, interdum elementum diam. Pellentesque varius tincidunt commodo. Proin id justo scelerisque risus porttitor consequat eget mollis leo. Maecenas quis lacus sem. Suspendisse tincidunt urna posuere ante dictum bibendum. Proin ac condimentum elit, mollis dignissim lorem.</span>
            </div>
        </main>
    );
}
